"""Pre-computed budget suggestion model.

Suggestions are generated by the daily Celery task (refresh_budget_suggestions)
and stored here so the frontend can read them instantly without running a
full spending analysis on every page load.

Each row represents one suggestion for an org (and optionally a specific user).
Rows are replaced wholesale on each refresh — no incremental updates.
"""

import uuid

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
)
from sqlalchemy.dialects.postgresql import UUID

from app.core.database import Base
from app.utils.datetime_utils import utc_now_lambda


class BudgetSuggestion(Base):
    """A pre-computed budget suggestion for an org (and optionally a user)."""

    __tablename__ = "budget_suggestions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Scope — org-wide or per-member
    organization_id = Column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # NULL = org-wide suggestion; non-null = scoped to this member's spending
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    # Category reference — one of these is set, not both
    # UUID: custom category (in categories table)
    category_id = Column(
        UUID(as_uuid=True),
        ForeignKey("categories.id", ondelete="CASCADE"),
        nullable=True,
    )
    # Raw lowercase category_primary string for provider categories (no UUID)
    category_primary_raw = Column(String(200), nullable=True)

    # Display name shown in the UI
    category_name = Column(String(200), nullable=False)

    # Suggested budget parameters
    suggested_amount = Column(Numeric(15, 2), nullable=False)
    # Stored as String — budgetperiod enum already exists from budgets table.
    # Values match BudgetPeriod: "monthly", "quarterly", "semi_annual", "yearly"
    suggested_period = Column(String(20), nullable=False)

    # Supporting stats (shown in the card)
    avg_monthly_spend = Column(Numeric(15, 2), nullable=False)
    total_spend = Column(Numeric(15, 2), nullable=False)
    month_count = Column(Integer, nullable=False)
    transaction_count = Column(Integer, nullable=False)

    # When this suggestion was computed
    generated_at = Column(DateTime, default=utc_now_lambda, nullable=False)

    __table_args__ = (
        # Fast lookup: "give me all org-wide suggestions" or "all for user X"
        Index("ix_budget_suggestions_org_user", "organization_id", "user_id"),
        # Staleness check: find suggestions older than N hours
        Index("ix_budget_suggestions_generated_at", "generated_at"),
    )
