"""add_property_vehicle_valuation_fields

Revision ID: 023448db874a
Revises: fe399652318d
Create Date: 2026-02-20 11:42:06.187562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023448db874a'
down_revision: Union[str, None] = 'fe399652318d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('property_address', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('property_zip', sa.String(length=10), nullable=True))
    op.add_column('accounts', sa.Column('vehicle_vin', sa.String(length=17), nullable=True))
    op.add_column('accounts', sa.Column('vehicle_mileage', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('last_auto_valued_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'last_auto_valued_at')
    op.drop_column('accounts', 'vehicle_mileage')
    op.drop_column('accounts', 'vehicle_vin')
    op.drop_column('accounts', 'property_zip')
    op.drop_column('accounts', 'property_address')
    # ### end Alembic commands ###
