"""add_market_cap_classification_to_holdings

Revision ID: 1eabc35bacee
Revises: c7d8e9f1a2b3
Create Date: 2026-02-14 16:28:06.451848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eabc35bacee'
down_revision: Union[str, None] = 'c7d8e9f1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_holdings_account_id', table_name='holdings')
    op.drop_index('ix_holdings_organization_id', table_name='holdings')
    op.drop_index('ix_holdings_ticker', table_name='holdings')
    op.drop_table('holdings')
    op.drop_index('ix_categories_plaid_name', table_name='categories')
    op.create_index(op.f('ix_categories_plaid_category_name'), 'categories', ['plaid_category_name'], unique=False)
    op.drop_constraint('labels_parent_label_id_fkey', 'labels', type_='foreignkey')
    op.drop_column('labels', 'parent_label_id')
    op.drop_index('ix_transactions_cursor_account', table_name='transactions')
    op.drop_index('ix_transactions_cursor_org', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_cursor_org', 'transactions', ['organization_id', sa.text('date DESC'), sa.text('created_at DESC'), sa.text('id DESC')], unique=False)
    op.create_index('ix_transactions_cursor_account', 'transactions', ['account_id', sa.text('date DESC'), sa.text('created_at DESC'), sa.text('id DESC')], unique=False)
    op.add_column('labels', sa.Column('parent_label_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('labels_parent_label_id_fkey', 'labels', 'labels', ['parent_label_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_categories_plaid_category_name'), table_name='categories')
    op.create_index('ix_categories_plaid_name', 'categories', ['plaid_category_name'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('shares', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=False),
    sa.Column('cost_basis_per_share', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_cost_basis', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('current_price_per_share', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('current_total_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('price_as_of', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('asset_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='holdings_account_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='holdings_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='holdings_pkey')
    )
    op.create_index('ix_holdings_ticker', 'holdings', ['ticker'], unique=False)
    op.create_index('ix_holdings_organization_id', 'holdings', ['organization_id'], unique=False)
    op.create_index('ix_holdings_account_id', 'holdings', ['account_id'], unique=False)
    # ### end Alembic commands ###
