"""add_label_id_to_recurring_transactions

Revision ID: c71ac9284b97
Revises: e646fa2a146a
Create Date: 2026-02-20 14:00:56.507749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71ac9284b97'
down_revision: Union[str, None] = 'e646fa2a146a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transactions', sa.Column('label_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'recurring_transactions', 'labels', ['label_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recurring_transactions', type_='foreignkey')
    op.drop_column('recurring_transactions', 'label_id')
    # ### end Alembic commands ###
