"""add_is_archived_and_is_no_longer_found_to_recurring_transactions

Revision ID: e646fa2a146a
Revises: e3f4a5b6c7d8
Create Date: 2026-02-20 13:52:45.699781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e646fa2a146a'
down_revision: Union[str, None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('recurring_transactions', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('recurring_transactions', sa.Column('is_no_longer_found', sa.Boolean(), nullable=False, server_default=sa.text('false')))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_transactions', 'is_no_longer_found')
    op.drop_column('recurring_transactions', 'is_archived')
    # ### end Alembic commands ###
