"""Add budget_suggestions table for pre-computed suggestions

Revision ID: s1u2g3g4e5s6
Revises: p1m2a3u4d5i6
Create Date: 2026-03-21

Stores pre-computed budget suggestions generated by the daily Celery task.
Each suggestion is scoped to an org (user_id=NULL) or a specific member.
Rows are replaced wholesale on each refresh.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "s1u2g3g4e5s6"
down_revision: Union[str, None] = "p1m2a3u4d5i6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "budget_suggestions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("category_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("category_primary_raw", sa.String(200), nullable=True),
        sa.Column("category_name", sa.String(200), nullable=False),
        sa.Column(
            "suggested_amount", sa.Numeric(15, 2), nullable=False
        ),
        # Use String here — budgetperiod enum already exists from the budgets table.
        # SQLAlchemy will cast correctly on read via the ORM model.
        sa.Column("suggested_period", sa.String(20), nullable=False),
        sa.Column("avg_monthly_spend", sa.Numeric(15, 2), nullable=False),
        sa.Column("total_spend", sa.Numeric(15, 2), nullable=False),
        sa.Column("month_count", sa.Integer, nullable=False),
        sa.Column("transaction_count", sa.Integer, nullable=False),
        sa.Column("generated_at", sa.DateTime, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="CASCADE"
        ),
    )
    op.create_index(
        "ix_budget_suggestions_org_user",
        "budget_suggestions",
        ["organization_id", "user_id"],
    )
    op.create_index(
        "ix_budget_suggestions_generated_at",
        "budget_suggestions",
        ["generated_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_budget_suggestions_generated_at", "budget_suggestions")
    op.drop_index("ix_budget_suggestions_org_user", "budget_suggestions")
    op.drop_table("budget_suggestions")
