"""
State income tax rates for 2025/2026.
Simplified flat-rate approximations for common states.
No-income-tax states return 0.
Sources: state revenue department websites.
Updated for 2025 rate changes: AZ (2.5% flat), IA (3.8% flat),
NC (4.25% from 4.5%), OH (reduced top rate).
"""

# State -> approximate effective rate as decimal (not bracket-based, simplified flat approx)
# For accuracy, we use the rate at ~$75,000 AGI which covers most users
STATE_TAX_RATES: dict[str, float] = {
    # No income tax states
    "AK": 0.0,
    "FL": 0.0,
    "NV": 0.0,
    "NH": 0.0,
    "SD": 0.0,
    "TN": 0.0,
    "TX": 0.0,
    "WA": 0.0,
    "WY": 0.0,
    # Flat rate states
    "CO": 0.044,
    "IL": 0.0495,
    "IN": 0.0315,
    "KY": 0.045,
    "MA": 0.05,
    "MI": 0.0425,
    "NC": 0.0425,  # 4.25% from 2025 (reduced from 4.5%/4.75%)
    "PA": 0.0307,
    "UT": 0.0485,
    # Progressive states (effective rate at ~$75k)
    "AL": 0.05,
    "AZ": 0.025,
    "AR": 0.047,
    "CA": 0.093,
    "CT": 0.065,
    "DE": 0.066,
    "GA": 0.055,
    "HI": 0.08,
    "ID": 0.058,
    "IA": 0.038,  # 3.8% flat from 2025
    "KS": 0.057,
    "LA": 0.04,
    "ME": 0.075,
    "MD": 0.0575,
    "MN": 0.0785,
    "MS": 0.05,
    "MO": 0.048,
    "MT": 0.069,
    "NE": 0.0584,
    "NJ": 0.0637,
    "NM": 0.059,
    "NY": 0.0685,
    "ND": 0.0264,
    "OH": 0.035,  # Reduced top rate from 2025
    "OK": 0.0475,
    "OR": 0.099,
    "RI": 0.0599,
    "SC": 0.07,
    "VT": 0.066,
    "VA": 0.0575,
    "WV": 0.065,
    "WI": 0.0765,
    "DC": 0.085,
}

STATE_NAMES: dict[str, str] = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "Washington D.C.",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
}
